### ISSUE TITLE
Could you please share your enclosure sources?

### ISSUE THREAD

**Issue by tpimh** [aleh/appreviewprinter#1]
![image](https://user-images.githubusercontent.com/1071872/88361639-614b7880-cd82-11ea-94d1-7fc06ee419a5.png)
I really like your 3D printed enclosure for this project. Could you please share it's source or STL files?

**Comment by aleh** [comment]
Hey! Thanks for the interest. Just committed both Fusion 360 sources and STL files.

**Comment by tpimh** [comment]
Thank you very much!
